### ISSUE TITLE
Test::More dependency not mentioned

### ISSUE THREAD

**Issue by WalterSmuts** [torbiak/git-autofixup#29]
Following the installation instructions in the README does not work on a clean systen AFAICT. i.e. `cpan -i App::Git::Autofixup`. You also need to `cpan -i Test::More`.

**Comment by torbiak** [comment]
I've been careful only to use modules that are in `perldoc perlmodlib` for 5.8.4, and Test::More is in there, too. When I look at a few modules on the CPAN I see some people putting `Test::More => 0` in their MakeMaker TEST_REQUIRES hash, but others don't despite using it. perlmodlib says some standard modules aren't always installed, but I can't imagine why a distribution of perl wouldn't include Test::More.

Do you know more about the situation and what conventional practice is for dependencies on modules in perlmodlib? I've been looking through the perl manpages, the MakeMaker docs, and searching online, but haven't found any definitive guidance. Should I put all my standard module dependencies in PREREQ_PM? (The MakeMaker that comes with 5.8.4 doesn't have TEST_REQUIRES yet.)

**Comment by torbiak** [comment]
Out of curiousity, which Perl distribution are you using, and which OS?

**Comment by torbiak** [comment]
After some more reading, it does seem like a good idea in general to include core modules in the list of dependencies, mostly since some Perl distributions don't distribute all the modules, and also because core modules can become non-core. This next point doesn't apply to git-autofixup currenlty, but for "dual-life" core modules that also live on the CPAN, a module distribution might require a newer version of the module than is included in core for older versions of Perl, and thus need to include that newer version in its list of dependencies.

The most useful advice I found was on StackOverflow: [Should I put core modules in the PREREQ_PM section of a Makefile.PL?](https://stackoverflow.com/questions/20905407/should-i-put-core-modules-in-the-prereq-pm-section-of-a-makefile-pl)

**Comment by WalterSmuts** [comment]
> Out of curiousity, which Perl distribution are you using, and which OS?

OS: Amazon Linux 2 I think
Perl: v5.16.3

**Comment by torbiak** [comment]
Thanks for the ticket, Walter. I was uninformed about this aspect of Perl packaging. I'll upload a new release shortly.

I wasn't able to find any specific information about why Test::More isn't included in Amazon Linux. I have seen that Pod::Usage (core since 5.6.0) isn't included with the perl distributed with Git for Windows, though, since they use their own web-based help system instead of man pages.

**Comment by WalterSmuts** [comment]
> Thanks for the ticket, Walter. I was uninformed about this aspect of Perl packaging. I'll upload a new release shortly.

No worries. I'm way more uninformed :)
