### ISSUE TITLE
commit_fixup and dequote_diff_filename break when diff.srcPrefix & dstPrefix are not a/ and b/

### ISSUE THREAD

**Issue by 1ace** [torbiak/git-autofixup#31]
These two functions hard-code `a/` and `b/`, which worked fine on my machine until I changed the settings to use `./` (`git config set --global diff.srcPrefix ./` and same for `dstPrefix`) so that I could copy/paste these paths without having to manually edit them all the time.

Now, I'm getting `error: ./src/some/file/name: does not exist in index`.

Could you please update these functions to query the current values instead of hard-coding them? I would send a PR but perl is not in my repertoire :sweat_smile:
The commands you'll need are `git config get --default=a/ diff.srcPrefix` and `git config get --default=b/ diff.dstPrefix` :wink:

Thanks for making this awesome tool btw! I've been using it for a few years and it's really convenient :muscle:

**Comment by torbiak** [comment]
Thanks for the report! Yeah, looks like the ability to configure the src/dst prefix was added earlier this year with Git 2.45. For `commit_fixup()`, git apparently accepts diffs with any single-component prefix regardless what `diff.{src,dst}Prefix` and `diff.mnemonicPrefix` are set to, and multi-component prefixes can never be used, even if they match `diff.{src,dst}Prefix`. Also, when `diff.mnemonicPrefix` is true it appears to override `diff.{src,dst}Prefix` when writing diffs, so that needs to be taken into account.

**Comment by torbiak** [comment]
Actually, it seems much easier to deal with this by consistently using `--no-prefix` when generating diffs and correspondingly giving `-p0` to `git apply` as necessary so it doesn't strip any path components. `commit_fixup()` doesn't need to be changed, since the default behaviour of `git apply` is to strip one path component (see the help for its `-p` option).

**Comment by torbiak** [comment]
I've uploaded a new release with the fix to the CPAN and I expect it will be available soon.

**Comment by 1ace** [comment]
Thanks for the quick turnaround!  I raise an issue at the end of one day and the fix is released to prod the next morning :muscle:

I tested the new version and everything works as intended, thank you so much!  And yeah, I agree with you, `diff --no-prefix | apply -p0` is a much better solution than trying to handles the various kinds of prefixes :+1:
